# Generated by Django 5.1.6 on 2025-05-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0024_alter_customer_mobile_alter_customer_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_group_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
