# Generated by Django 5.1.6 on 2025-02-14 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_preorder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="PreOrder",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
